/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Response after updating user quota
 * @export
 * @interface QuotaUpdateResponse
 */
export interface QuotaUpdateResponse {
    /**
     * Whether the update was successful
     * @type {boolean}
     * @memberof QuotaUpdateResponse
     */
    'success': boolean;
    /**
     * Status message
     * @type {string}
     * @memberof QuotaUpdateResponse
     */
    'message': string;
    /**
     * User ID that was updated
     * @type {string}
     * @memberof QuotaUpdateResponse
     */
    'user_id': string;
    /**
     * Type of quota that was updated
     * @type {string}
     * @memberof QuotaUpdateResponse
     */
    'quota_type': string;
    /**
     * Previous quota limit
     * @type {number}
     * @memberof QuotaUpdateResponse
     */
    'old_limit': number;
    /**
     * New quota limit
     * @type {number}
     * @memberof QuotaUpdateResponse
     */
    'new_limit': number;
}

