/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request to update user quota
 * @export
 * @interface QuotaUpdateRequest
 */
export interface QuotaUpdateRequest {
    /**
     * Type of quota to update
     * @type {string}
     * @memberof QuotaUpdateRequest
     */
    'quota_type': QuotaUpdateRequestQuotaTypeEnum;
    /**
     * New quota limit
     * @type {number}
     * @memberof QuotaUpdateRequest
     */
    'new_limit': number;
}

export const QuotaUpdateRequestQuotaTypeEnum = {
    max_collection_count: 'max_collection_count',
    max_document_count: 'max_document_count',
    max_document_count_per_collection: 'max_document_count_per_collection',
    max_bot_count: 'max_bot_count'
} as const;

export type QuotaUpdateRequestQuotaTypeEnum = typeof QuotaUpdateRequestQuotaTypeEnum[keyof typeof QuotaUpdateRequestQuotaTypeEnum];


