openapi: 3.1.0
info:
  title: ApeRAG API
  description: ApeRAG API Documentation
  version: 1.0.0
servers:
  - url: /api/v1
    description: API v1
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
    CookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
paths:
  # bots
  /bots:
    $ref: './paths/bots.yaml#/bots'
  /bots/{bot_id}:
    $ref: './paths/bots.yaml#/bot'
  /bots/{bot_id}/flow:
    $ref: './paths/flow.yaml#/flow'
  /bots/{bot_id}/flow/debug:
    $ref: './paths/bots.yaml#/debugFlow'

  # chats
  /bots/{bot_id}/chats:
    $ref: './paths/chats.yaml#/chats'
  /bots/{bot_id}/chats/{chat_id}:
    $ref: './paths/chats.yaml#/chat'
  /bots/{bot_id}/chats/{chat_id}/messages/{message_id}:
    $ref: './paths/message.yaml#/message'

  # collections
  /collections:
    $ref: './paths/collections.yaml#/collections'
  /collections/{collection_id}:
    $ref: './paths/collections.yaml#/collection'
  /collections/{collection_id}/summary/generate:
    $ref: './paths/collections.yaml#/summary_generate'
  /collections/{collection_id}/documents:
    $ref: './paths/collections.yaml#/documents'
  /collections/{collection_id}/documents/{document_id}:
    $ref: './paths/collections.yaml#/document'
  /collections/{collection_id}/documents/{document_id}/rebuild_indexes:
    $ref: './paths/collections.yaml#/rebuild_indexes'
  /collections/{collection_id}/documents/{document_id}/preview:
    $ref: './paths/collections.yaml#/document_preview'
  /collections/{collection_id}/documents/{document_id}/object:
    $ref: './paths/collections.yaml#/document_object'
  /collections/{collection_id}/searches:
    $ref: './paths/collections.yaml#/searches'
  /collections/{collection_id}/searches/{search_id}:
    $ref: './paths/collections.yaml#/search_detail'

  # settings
  /settings:
    $ref: './paths/settings.yaml#/settings'
  /settings/test_mineru_token:
    $ref: './paths/misc.yaml#/test_mineru_token'

  # graphs
  /collections/{collection_id}/graphs/labels:
    $ref: './paths/collections.yaml#/graph_labels'
  /collections/{collection_id}/graphs:
    $ref: './paths/collections.yaml#/graph'
  /collections/{collection_id}/graphs/nodes/merge:
    $ref: './paths/collections.yaml#/graph_nodes_merge'
  /collections/{collection_id}/graphs/merge-suggestions:
    $ref: './paths/collections.yaml#/graph_merge_suggestions'
  /collections/{collection_id}/graphs/merge-suggestions/{suggestion_id}/action:
    $ref: './paths/collections.yaml#/graph_suggestion_action'

  # apikeys
  /apikeys:
    $ref: './paths/apikeys.yaml#/apikeys'
  /apikeys/{apikey_id}:
    $ref: './paths/apikeys.yaml#/apikey'

  # models
  /available_models:
    $ref: './paths/models.yaml#/availableModels'

  # llm configuration
  /llm_configuration:
    $ref: './paths/llm_configuration.yaml#/llmConfiguration'
  /llm_providers:
    $ref: './paths/llm_configuration.yaml#/llmProviders'
  /llm_providers/{provider_name}:
    $ref: './paths/llm_configuration.yaml#/llmProvider'
  /llm_providers/{provider_name}/models:
    $ref: './paths/llm_configuration.yaml#/llmProviderModels'
  /llm_providers/{provider_name}/models/{api}/{model}:
    $ref: './paths/llm_configuration.yaml#/llmProviderModel'
  /llm_provider_models:
    $ref: './paths/llm_configuration.yaml#/llmProviderModelsList'

  # llm services
  /embeddings:
    $ref: './paths/llm.yaml#/embeddings'
  /rerank:
    $ref: './paths/llm.yaml#/rerank'

  # config
  /config:
    $ref: './paths/config.yaml#/config'
  /prompt-templates:
    $ref: './paths/prompt_templates.yaml#/promptTemplates'

  # audit
  /audit-logs:
    $ref: './paths/audit.yaml#/audit_logs'
  /audit-logs/{audit_id}:
    $ref: './paths/audit.yaml#/audit_log_detail'

  # users
  /invite:
    $ref: './paths/auth.yaml#/invite'
  /invitations:
    $ref: './paths/auth.yaml#/invitations'
  /register:
    $ref: './paths/auth.yaml#/register'
  /login:
    $ref: './paths/auth.yaml#/login'
  /logout:
    $ref: './paths/auth.yaml#/logout'
  /users:
    $ref: './paths/auth.yaml#/users'
  /user:
    $ref: './paths/auth.yaml#/user'
  /change-password:
    $ref: './paths/auth.yaml#/changePassword'
  /users/{user_id}:
    $ref: './paths/auth.yaml#/deleteUser'

  # quotas
  /quotas:
    $ref: './paths/quotas.yaml#/quotas'
  /quotas/{user_id}:
    $ref: './paths/quotas.yaml#/quota'
  /quotas/{user_id}/recalculate:
    $ref: './paths/quotas.yaml#/quota_recalculate'

  # web services
  /web/search:
    $ref: './paths/web.yaml#/webSearch'
  /web/read:
    $ref: './paths/web.yaml#/webRead'
  /agent/message:
    $ref: './paths/agent.yaml'
