"""empty message

Revision ID: 1c57dc0b71d2
Revises: b3a2c218442f
Create Date: 2025-07-24 11:10:48.150443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c57dc0b71d2'
down_revision: Union[str, None] = 'b3a2c218442f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_account',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('oauth_name', sa.String(length=100), nullable=False),
    sa.Column('access_token', sa.String(length=1024), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sa.String(length=1024), nullable=True),
    sa.Column('account_id', sa.String(length=320), nullable=False),
    sa.Column('account_email', sa.String(length=320), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_account_account_id'), 'oauth_account', ['account_id'], unique=False)
    op.create_index(op.f('ix_oauth_account_oauth_name'), 'oauth_account', ['oauth_name'], unique=False)
    op.alter_column('api_key', 'status',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('audit_log', 'resource_type',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_comment='Resource type',
               existing_nullable=True)
    op.alter_column('bot', 'type',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('bot', 'status',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('chat', 'peer_type',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('chat', 'status',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('collection', 'status',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('collection', 'type',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('collection_summary', 'status',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('document', 'status',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('document_index', 'index_type',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('document_index', 'status',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('graph_index_merge_suggestions', 'status',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('invitation', 'role',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('llm_provider_models', 'api',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('message_feedback', 'type',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('message_feedback', 'tag',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('message_feedback', 'status',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('model_service_provider', 'status',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('model_service_provider', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('message_feedback', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=True)
    op.alter_column('message_feedback', 'tag',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=True)
    op.alter_column('message_feedback', 'type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=True)
    op.alter_column('llm_provider_models', 'api',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('invitation', 'role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('graph_index_merge_suggestions', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('document_index', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('document_index', 'index_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('document', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('collection_summary', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('collection', 'type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('collection', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('chat', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('chat', 'peer_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('bot', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('bot', 'type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('audit_log', 'resource_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_comment='Resource type',
               existing_nullable=True)
    op.alter_column('api_key', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.drop_index(op.f('ix_oauth_account_oauth_name'), table_name='oauth_account')
    op.drop_index(op.f('ix_oauth_account_account_id'), table_name='oauth_account')
    op.drop_table('oauth_account')
    # ### end Alembic commands ###
